apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (e.g. browser)
  ports:
    - name: http
      port: 80
      nodePort: 30080
  selector:
    app: webapp
  type: NodePort # ClusterIP | LoadBalancer(only Cloud)


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
  selector:
    app: queue
  type: NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: position-tracker
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: api-gateway
  type: ClusterIP